# Site settings
title: Đức Nguyễn - Cyber Security Portfolio
description: Building secure systems, one line at a time
url: "https://davidnguyen26.github.io"
baseurl: "/cyber-template"

# Author
author:
  name: Đức Nguyễn
  email: contact@example.com
  github: davidnguyen26
  linkedin: your-linkedin

# Build settings
markdown: kramdown
permalink: /blog/:year/:month/:day/:title/

# Kramdown settings
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

# Exclude files
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md
  - .git
  - .gitignore

# Include files
include:
  - _pages

# Collections
collections:
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Feed settings
feed:
  path: feed.xml